### PR TITLE
Fix issue #31

### LINKED ISSUE #31: Bug: Parentheses inside text node are considered invalid hence expansion doesn't work
`div{ foo (bar) baz }` should expand to `<div>foo (bar) baz</div>`. But currently this does not work because it's considered an invalid expression due to the following code

https://github.com/microsoft/vscode-emmet-helper/blob/05f86590aa88b88c8e4878c57b7f33b8b3256ed9/src/emmetHelper.ts#L492-L496

Restricting `(`  and `)` to be only next to `>`, `+`, `*` or  `^` misses the case where `(` or`)` are inside `{` and `}` that is in a text node.

Actual behavior:

Expected behavior (as seen on [emmet's docs](https://docs.emmet.io/)):

I'll be sending a PR soon!

### LINKED ISSUE #77776: Bug: Emmet expansion doesn't work when parentheses are used inside text node
Already being tracked via [vscode-emmet-helper #31](https://github.com/microsoft/vscode-emmet-helper/issues/31). I thought I should also file an issue here. I also opened a [PR that fixes this](https://github.com/microsoft/vscode-emmet-helper/pull/32).

### PR DESCRIPTION
**Pull request by devanshj**
Fixes [#31](https://github.com/microsoft/vscode-emmet-helper/issues/31)
Fixes [microsoft/vscode #77776](https://github.com/microsoft/vscode/issues/77776)

~~The RegEx `/\{[^\}]*\(.*\)[^\{]*\}/` [looks good to me](https://regexr.com/4hiq3)...~~
~~Heh nope, doesn't allow `div { a (b c }` and even `div { a ((( }`. One fix could be to use `/\{[^\}\{]*\}/` but that would allow things like `div { a }(b){ c}` also...~~

~~So till I figure out a good way to fix this, consider this PR as a draft.~~
Okay so with the second commit the fix looks good to me. I have also added a bunch of tests. It did involve a little trial-and-error but I guess the tests are covering enough cases.

Also there was a minor mistake where the condition does a `/\(/.test(abbreviation) && /\)/.test(abbreviation)` to check if it has parentheses but it should be `||` instead.

/cc @ramya-rao-a @octref

### CODE REVIEW

File: src/emmetHelper.ts [hunk 1]
```diff
@@ -490,8 +490,8 @@ export function isAbbreviationValid(syntax: string, abbreviation: string): boole
 		return parseInt(multipleMatch[1], 10) <= 100
 	}
 	// Its common for users to type (sometextinsidebrackets), this should not be treated as an abbreviation
-	// Grouping in abbreviation is valid only if preceeded/succeeded with one of the symbols for nesting, sibling, repeater or climb up
-	if (!/\(.*\)[>\+\*\^]/.test(abbreviation) && !/[>\+\*\^]\(.*\)/.test(abbreviation) && /\(/.test(abbreviation) && /\)/.test(abbreviation)) {
+	// Grouping in abbreviation is valid only if it's inside a text node or preceeded/succeeded with one of the symbols for nesting, sibling, repeater or climb up
+	if ((/\(/.test(abbreviation) || /\)/.test(abbreviation)) && !/\{[^\}\{]*[\(\)]+[^\}\{]*\}(?:[>\+\*\^]|$)/.test(abbreviation) && !/\(.*\)[>\+\*\^]/.test(abbreviation) && !/[>\+\*\^]\(.*\)/.test(abbreviation)) {
```
Comment (devanshj) [inline src/emmetHelper.ts:494]: If it's not obvious then the `(?:[>\+\*\^]|$)` part is to invalidate abbreviations like `div{ a }( b ){ c }`.

**Comment by octref** [comment]
I tried `div{ foo ((( abc }` and `div{ a (b) c}+div{ a (( }`, both doesn't expand on emmet doc. Why are the valid expansions with unbalanced parens?

**Comment by devanshj** [comment]
@octref I think it's better if we don't bother about anything that's inside a text node. Because parenthesis inside text node don't mean anything, as in whatever is inside `{` and `}` just becomes the text node in the expansion, it doesn't make sense to require balancing there.

Practical example: Let's say you copy 10 lines of text from somewhere, use emmet to wrap each line with `li` and one of them has unbalanced parenthesis I would expect the text node to also have unbalanced parenthesis rather than not expanding the expression at all.

But now the problem is emmet doesn't expand them (I understood now was away from keyboard) but they are still valid expressions in principle in my opinion.

Now I guess we have two options:
1. Fix emmet so it expands unbalanced parenthesis inside text node
2. Invalidate unbalanced parenthesis inside text node

(TLDR:) I think for now we should invalidate unbalanced parenthesis, if you're fine with that I can modify the PR accordingly.

**Comment by devanshj** [comment]
Also, what's funny is looks like emmet has a naive bracket matching in-built because `div{ a (b c}+div{ a ) }` expands on [docs.emmet.io](https://docs.emmet.io/) even though the brackets are unbalanced within each text node but balanced overall 😅 So I guess we should do the same with our validation.

**Comment by devanshj** [comment]
Okay, I just thought this through. So as far I can tell `isAbbreviationValid` is actually a pre-validator instead of a complete validator of the expression. We are using emmet's internal validation in addition to this by checking if it throws or not.

https://github.com/microsoft/vscode-emmet-helper/blob/05f86590aa88b88c8e4878c57b7f33b8b3256ed9/src/emmetHelper.ts#L127-L138

So I guess it's fair to treat unbalanced parenthesis as valid since they'll be rejected by the thrown error. I think this is will be the best solution in this mess. So imo this PR is sufficiently good to go.

Also sorry that this got more complex and is taking longer than anticipated because I understand you have more important issues to fix.

**Comment by devanshj** [comment]
@octref Also `require("`[./expand/expand-full.js](https://github.com/microsoft/vscode-emmet-helper/blob/master/src/expand/expand-full.js)`").expand("div{ foo ((( abc }")` returns `<div>div{ foo ((( abc }</div>` intsead of throwing which is nice but then I don't know then why  [testExpand](https://github.com/microsoft/vscode-emmet-helper/blob/master/src/test/expand.test.ts)`("html", "div{ foo ((( abc }", "<div>div{ foo ((( abc }</div>")` throws an error that the expansion is not in completion list 🤔 ~At this point I have no idea what's going on xD~

Okay so now the problem is that `require("@emmetio/extract-abbreviation")("div{ foo ((( abc }"))` matches `"abc }"` instead of whole text hence the `testExpand` fails.

**Comment by octref** [comment]
In the cases when you can't tell, we can be more liberal than emmet in accepting inputs (as long as it can expand).

**Comment by devanshj** [comment]
Sorry for the mess & spam here's a summarised answer:
1. "div{ foo ((( abc }" is valid because parenthesis don't mean anything between `{`, `}` and thus we shouldn't require to balance them.
2. `require("./expand/expand-full.js").expand("div{ foo ((( abc }")` successfully expands to `<div> foo ((( abc </div>`
3. The reason it won't expand on [docs.emmet.io](docs.emmet.io) and even in VSCode (`testExpand("html", "div{ foo ((( abc }", "<div> foo ((( abc </div>")` fails) is because `@emmetio/extract-abbreviation` doesn't recognize it.

Action point:
1. Fix `@emmetio/extract-abbreviation` so that `require("@emmetio/extract-abbreviation")("div{ foo ((( abc }")` returns `{ abbreviation: "div{ foo ((( abc }" }` (currently returns `{ abbreviation: "abc }" }`
2. I'm not sure but I guess we should merge this PR and then fix `@emmetio/extract-abbreviation` because this PR alone also will fix things for balanced parenthesis case.

**Comment by devanshj** [comment]
> In the cases when you can't tell, we can be more liberal than emmet in accepting inputs (as long as it can expand).

Yesss exactly. But now the problem is unbalanced parenthesis do expand theoretically but `@emmetio/extract-abbreviation` doesn't recognize them.

File: src/test/emmetHelper.test.ts [hunk 2]
```diff
@@ -33,13 +33,13 @@ const expectedBemCommentFilterOutputDocs = expectedBemCommentFilterOutput.replac
 
 describe('Validate Abbreviations', () => {
 	it('should return true for valid abbreviations', () => {
-		const htmlAbbreviations = ['ul>li', 'ul', 'h1', 'ul>li*3', '(ul>li)+div', '.hello', '!', '#hello', '.item[id=ok]', '.', '.foo'];
+		const htmlAbbreviations = ['ul>li', 'ul', 'h1', 'ul>li*3', '(ul>li)+div', '.hello', '!', '#hello', '.item[id=ok]', '.', '.foo', 'div{ foo (bar) baz }', 'div{ foo ((( abc }', 'div{()}', 'div{ a (b) c}', 'div{ a (b) c}+div{ a (( }'];
```
Comment (octref) [inline src/test/emmetHelper.test.ts]:
```suggestion
		const htmlAbbreviations = [
			'ul>li',
			'ul',
			'h1',
			'ul>li*3',
			'(ul>li)+div',
			'.hello',
			'!',
			'#hello',
			'.item[id=ok]',
			'.',
			'.foo',
			'div{ foo (bar) baz }',
			'div{ foo ((( abc }',
			'div{()}',
			'div{ a (b) c}',
			'div{ a (b) c}+div{ a (( }'
		];
```

**Review by octref — APPROVED** [review]

**Comment by octref** [comment]
> Fix @emmetio/extract-abbreviation so that require("@emmetio/extract-abbreviation")("div{ foo ((( abc }") returns { abbreviation: "div{ foo ((( abc }" } (currently returns { abbreviation: "abc }" }

Sounds good. You can send a PR to https://github.com/emmetio/extract-abbreviation#readme. Thanks a lot for looking into this!

**Comment by devanshj** [comment]
> Sounds good. You can send a PR to emmetio/extract-abbreviation#readme. Thanks a lot for looking into this!

Yeah I'm looking into fixing it, once I fix it I'll send a PR till the time I would also file an issue there. Also the pleasure is all mine! :D

**Comment by devanshj** [comment]
Hi @octref so now emmet PR [#571](https://github.com/emmetio/emmet/pull/571), [#569](https://github.com/emmetio/emmet/pull/569) that were responsible for fixing the extraction are merged.

I tried to migrate from `@emmetio/extract-abbreviation` & `src/expand/expand-full.js` to the newer `emmet@2.0.0` but looks like it isn't trivial.

Also I went through almost all issues on vscode repo that were labelled as emmet and a lot of them can be just fixed by updating to v2 since @sergeche has fixed a bunch of issues of `@emmetio/extract-abbreviation` in the newer emmet like [#20](https://github.com/emmetio/expand-abbreviation/issues/20) (fixes [#45724](https://github.com/microsoft/vscode/issues/45724)), [#17](https://github.com/emmetio/expand-abbreviation/issues/17), [#23](https://github.com/emmetio/expand-abbreviation/issues/23) (fixes [#52345](https://github.com/microsoft/vscode/issues/52345)), [#24](https://github.com/emmetio/expand-abbreviation/issues/24) (fixes [#59172](https://github.com/microsoft/vscode/issues/59172)), maybe more.

Also I was kinda verifying if the newer version fixes some issues and it does here's the [StackBlitz](https://stackblitz.com/edit/typescript-cgtujp?file=index.ts) that demonstrates it. Afaict [#63703](https://github.com/microsoft/vscode/issues/63703), [#80923](https://github.com/microsoft/vscode/issues/80923), [#59951](https://github.com/microsoft/vscode/issues/59951), [#71002](https://github.com/microsoft/vscode/issues/71002) and probably more can be closed with the newer emmet.

So I guess it will be worth migrating to the newer emmet, and also the older one's are deprecated so vscode will have to migrate to newer one at some point to take advantage of further developments

Also let me know if I should create an issue for migration instead of having all this written here.

**Comment by octref** [comment]
@devanshj Wow, thanks a lot for looking into this. Good work 👍 

Moving to emmet v2 makes sense. It just involves a lot of effort. I remember the reason we had `expand-full.js` as a single file was due to bundling issues. We can look into this again.

To start, I'd create an issue in vscode repo and link to all issues that would be fixed by upgrading to v2. I'll try to get some time in Oct/Nov to help you with it.

**Comment by devanshj** [comment]
@octref Thanks and welcome! 😁 And yeah I'll be down with helping with this as much as I can.

**Comment by BMBurstein** [comment]
Thanks to both of you. Is this still moving forward?

**Comment by devanshj** [comment]
@BMBurstein

> Thanks to both of you.

 You're welcome!

> Is this still moving forward?

PR #33 was ready to merge until I realised that it doesn't have full test coverage so I had to dig deeper that's when I found out it's a whole mess. I started rewriting it, even remodeling and that's when I realized we don't need this package seperately because it's not doing much. That's when I started patching [the extension itself](https://github.com/microsoft/vscode/tree/master/extensions/emmet/src) to not use this module (ie `vscode-emmet-helper`). Even that is still wip (I haven't pushed) and I haven't looked into it in a long time. I'll see if I can look into it soon :)

(You can see description of PR #33 on why I'm ditching this module)

So to answer your question, it's stagnant at the moment but I will work on migrating to `emmet@2.x.x` once I've time for it.
