### PR TITLE
fix: mark successive dots as noise and invalidate jinja syntax abbreviations 

### LINKED ISSUE #179422: Emmet suggestions produces incorrect Jinja syntax
Type: <b>Bug</b>

1. Open an HTML file.

2. Start typing a Jinja template tag like {% if %} 

3. Notice an Emmet suggestion pop up and accept it. Now the curly brackets are gone, which is invalid Jinja syntax.

You might wonder, why did I accept the suggestion?
1) It's easy to tab accept something without thinking, and I've accepted it many times without even noticing it called "Emmet suggestion"
2) Someone new to Jinja might think that Emmet knows more than they do, and trust the suggestion.

I ran into this myself personally and while running Flask workshops for developers new to Flask.

VS Code version: Code - Insiders 1.78.0-insider (Universal) (cbf35328c8357175b9cd747823f39ade987c3d3c, 2023-04-04T18:48:48.802Z)
OS version: Darwin arm64 22.4.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|7, 11, 10|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 29b0fda8-7569-499a-9770-cfbb5ac8c0cf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: simple-flask-server-example|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|unknown (5 x 0)|
|Memory (System)|8.74GB (0.01GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.1.0
remote-containers|ms-|0.289.0
vscode-eslint|dba|2.4.0
copilot-nightly|Git|1.79.10758
vscode-github-actions|git|0.25.3
python|ms-|2023.6.0
vscode-pylance|ms-|2023.4.10
jupyter|ms-|2023.3.1000892223
jupyter-keymap|ms-|1.1.0
jupyter-renderers|ms-|1.0.15

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
6233i204:30659907
pythonb192:30661256
functionswalk:30687959
pythonms35:30671666
0bg3d529:30680467
ecj1e332:30687743
pythonclientmv:30700173

```

</details>

### PR DESCRIPTION
**Pull request by iifawzi**
Hi, this PR should fix https://github.com/microsoft/vscode/issues/179422
let me know if it could be done in any better way

### CODE REVIEW

**Comment by iifawzi** [comment]
Hi @rzhao271, would appreciate if you can take a look whenever you have a time

File: src/emmetHelper.ts [hunk 1]
```diff
@@ -521,6 +521,14 @@ export function isAbbreviationValid(syntax: string, abbreviation: string): boole
 	if (syntax === 'jsx') {
 		return (jsxAbbreviationStartRegex.test(abbreviation) && htmlAbbreviationRegex.test(abbreviation));
 	}
+	
+	// Fix for jinja syntax https://github.com/microsoft/vscode/issues/179422
+	if (syntax === 'html') {
+		if (/^({%|{#|{{)/.test(abbreviation)) {
+		  return false;
```
Comment (rzhao271) [inline src/emmetHelper.ts]: The indent seems a bit off here. Also, the isStyleSheet check above already covers CSS and CSS-related languages and returns early, so if it is possible to type jinja syntax in other HTML-related languages too, then the outer `syntax === 'html'` condition can be removed.

File: src/emmetHelper.ts [hunk 2]
```diff
@@ -557,6 +565,12 @@ function isExpandedTextNoise(syntax: string, abbreviation: string, expandedText:
 		return false;
 	}
 
+	// users might write successive dots '..', '...' which shouldn't be treated as an abbreviation
+	const successiveDots = abbreviation.match(/^(\.{2,})$/);
```
Comment (rzhao271) [inline src/emmetHelper.ts]: Could this be changed to use `.test()` instead? Because of the comment and the fact that `successiveDots` is only used once, I'm thinking the const can be directly inlined into the if statement as well.
Lastly, are the parentheses needed around `\.{2,}`?

File: src/test/expand.test.ts [hunk 3]
```diff
@@ -289,4 +289,12 @@ describe('Wrap Abbreviations (more advanced)', () => {
...
 	testWrap('div', '<img src={`img/projects/${src}`} alt=\'\' />',
 		'<div><img src={`img/projects/${src}`} alt=\'\' /></div>', undefined, 'jsx');
+
+	// https://github.com/microsoft/vscode/issues/179422
+	testCountCompletions('html', '{% if value is prime %}', 0);
+	testCountCompletions('html', '{# comment #}', 0);
+	testCountCompletions('html', '{{ value }}', 0);
+	
+	// https://github.com/microsoft/vscode/issues/179422#issuecomment-1504099693
+	testCountCompletions('html', '..', 0);
```
Comment (rzhao271) [inline src/test/expand.test.ts:299]: Also add a test for a single dot to confirm that there is still a completion.

**Review by rzhao271 — COMMENTED** [review]
Thanks for the PR! I have added some comments

File: src/emmetHelper.ts (hunk 1 above)
Comment (iifawzi) [reply src/emmetHelper.ts]: I don't think it has a meaning at any of the html related languages, that's why I went with checking the syntax to be html, what do you think? @rzhao271

File: src/emmetHelper.ts (hunk 2 above)
Comment (iifawzi) [reply src/emmetHelper.ts]: yes you're right, no need to capture them, I will also push a commit to use test and inline it directly as you suggested

File: src/emmetHelper.ts (hunk 1 above)
Comment (iifawzi) [reply src/emmetHelper.ts]: The indentation seems to be only off in the diff here, it looks fine locally
image

Comment (rzhao271) [reply src/emmetHelper.ts]: If the abbreviation shouldn't be parsed as an Emmet abbreviation in any HTML-related language, then the outer condition can be removed.

**Comment by iifawzi** [comment]
Pushed the changes https://github.com/iifawzi/vscode-emmet-helper/tree/fix/jinga-successive--abbreviations, but for some reason they didn't reflect here. That's weird, I've never encountered this.

EDIT: ok it seems like there's an outage, https://www.githubstatus.com/

File: src/emmetHelper.ts (hunk 1 above)
Comment (iifawzi) [reply src/emmetHelper.ts]: resolved

**Review by rzhao271 — APPROVED** [review]

**Review by joyceerhl — APPROVED** [review]
