### PR TITLE
Fix vscode#118008

### LINKED ISSUE #118008: All of the directories in the array doesn't exist. Update emmet.extensionsPath setting
I have not configured this setting, so I'd expect to not see this error.

(Note this is only building from sources, disregard if you've already fixed)

image

### PR DESCRIPTION
**Pull request by lancewl**
Fix microsoft/vscode#118008
This PR fix the error message bug in `updateExtensionsPath` which caused by the update of default input type in the main repo.

### CODE REVIEW

File: src/emmetHelper.ts [hunk 1]
```diff
@@ -956,11 +956,20 @@ function getFormatters(syntax: string, preferences: any) {
 
 /**
  * Updates customizations from snippets.json and syntaxProfiles.json files in the directory configured in emmet.extensionsPath setting
+ * TODO: The input type of this setting has been changed on the vscode side. To support users with old version, the old input types are still accripted by this function.
```
Comment (rzhao271) [inline src/emmetHelper.ts]: Actually, considering how the library needs to be bumped up to be used in vscode, and that the current main branch of vscode already changes the parameter to [], do we still need to keep this?

Comment (lancewl) [reply src/emmetHelper.ts]: Hm, I am thinking about for those users not update to the newest version, they might still have old value types such like `null` or `string`, so if we just removed the old types from the function. It will crash raise an error for those users.

Comment (rzhao271) [reply src/emmetHelper.ts]: The main branch of vscode already has the migration function. Therefore, after we publish a new package for vscode-emmet-helper, we can directly use this package in vscode.
Also, only users of the new package will need to change their extensionsPath type.

File: src/emmetHelper.ts [hunk 2]
```diff
@@ -956,36 +956,21 @@ function getFormatters(syntax: string, preferences: any) {
...
-	}
-
 	let emmetExtensionsPathUri: URI | undefined;
 	let hasValidPath = false;
-	for (let emmetExtensionsPath of emmetExtensionsArray) {
+	for (let emmetExtensionsPath of emmetExtensionsPathSetting) {
 		if (emmetExtensionsPath) {
 			emmetExtensionsPath = emmetExtensionsPath.trim();
 		}
-		if (!emmetExtensionsPath) {
```
Comment (rzhao271) [inline src/emmetHelper.ts]: I'm not sure if taking out this line works. For example, if I set the extensions path to `["    ", "", " "]`, should that now give an error?

File: src/test/emmetHelper.test.ts [hunk 3]
```diff
@@ -459,12 +459,12 @@ describe('Test custom snippets', () => {
...
 	it('should use the first valid custom snippets from an array of extensions path', async () => {
 		const customSnippetKey = 'ch';
-		await updateExtensionsPath(null);
+		await updateExtensionsPath([]);
 		const expandOptionsWithoutCustomSnippets = getExpandOptions('css');
 		assert(!expandOptionsWithoutCustomSnippets.snippets);
 
 		// Use custom snippets from extensionsPathArray
-		const extensionsPathArray = ["./this/is/not/valid", extensionsPath]
+		const extensionsPathArray = ["./this/is/not/valid", extensionsPath[0]]
```
Comment (rzhao271) [inline src/test/emmetHelper.test.ts]: Maybe `...extensionsPath` instead of just `extensionsPath[0]`

File: src/emmetHelper.ts [hunk 4]
```diff
@@ -956,36 +956,21 @@ function getFormatters(syntax: string, preferences: any) {
...
  * @param emmetExtensionsPathSetting setting passed from emmet.extensionsPath. Supports multiple paths
  */
-export async function updateExtensionsPath(emmetExtensionsPathSetting: string | string[] | undefined | null, fs: FileService, workspaceFolderPath?: URI, homeDir?: URI): Promise<void> {
-	let emmetExtensionsArray: string[];
-
-	if (Array.isArray(emmetExtensionsPathSetting) && !emmetExtensionsPathSetting.length){
-		// default value of emmet.extensionsPath has been changed to empty array
-		// Do nothing if the input array is an empty array, since it means that users don't specify any settings
+export async function updateExtensionsPath(emmetExtensionsPathSetting: string[], fs: FileService, workspaceFolderPath?: URI, homeDir?: URI): Promise<void> {
+	if (!emmetExtensionsPathSetting.length){
```
Comment (rzhao271) [inline src/emmetHelper.ts]: Just noticed this line isn't formatted. I guess I should add a pre-commit hook to check this

File: src/emmetHelper.ts (hunk 2 above)
Comment (rzhao271) [reply src/emmetHelper.ts]: Actually nvm, imo it should. Marking as resolved.

Comment (lancewl) [reply src/emmetHelper.ts]: Oh wait this should not be removed. Will do a quick fix now.

Comment (lancewl) [reply src/emmetHelper.ts]: Oh should it return error? I think in the previous version we also accepted empty string.

File: src/emmetHelper.ts (hunk 1 above)
Comment (rzhao271) [reply src/emmetHelper.ts]: For reference: discussed offline, and we're keeping this part of the code so that users can set their extensionsPath like `["path1", "path2", ""]`. With this config, they get to explicitly turn off snippets if neither of the paths resolve (e.g. if they're on an environment where they don't want or care about having custom snippets).

**Review by rzhao271 — APPROVED** [review]
